// components/Navbar/Menu.tsx
import Link from "next/link";
import { Button } from "components/shared/Button.style";
import { LinkStyled } from "components/shared/Link.style";

const menu = [
  { name: "Home", href: "#home" },
  { name: "About", href: "#about" },
  { name: "Projects", href: "#projects" },
  { name: "Contact", href: "#contact", button: true },
];

function Menu(props: { className?: string; toggle?: () => void }) {
  const { className, toggle } = props;

  return (
    <ul className={className}>
      {menu.map(({ name, href, button }) => (
        <li key={name} onClick={toggle}>
          {button ? (
            <Link href={href}>
              <Button variant="primary">{name}</Button>
            </Link>
          ) : (
            <LinkStyled href={href}>{name}</LinkStyled>
          )}
        </li>
      ))}
    </ul>
  );
}

export default Menu;

// src/components/navbar/Menu.vue
<script lang="ts" setup>
const menu = [
  { name: "Home", href: "#home" },
  { name: "About", href: "#about" },
  { name: "Projects", href: "#projects" },
  { name: "Contact", href: "#contact", button: true },
];
</script>

<template>
  <ul>
    <li v-for="item in menu" :key="item.name">
      <a :href="item.href" :class="item.button ? 'btn--primary' : 'link'">
        {{ item.name }}
      </a>
    </li>
  </ul>
</template>
